-- -- services
-- local Players = game:GetService("Players")
-- local RunService = game:GetService("RunService")
-- local ServerScriptService = game:GetService("ServerScriptService")

-- -- ProfileStore
-- local ProfileStore = require(ServerScriptService.Server.Libraries.ProfileStore)

-- local function GetStoreName()
--     return RunService:IsStudio() and "Test" or "Live"
-- end

-- -- Access profile store
-- local PlayerStore = ProfileStore.New()